apiVersion: v1
kind: Service
metadata:
  name: {{ include "capstone-chart-openvas-notus-data.fullname" . }}
  labels:
    {{- include "capstone-chart-openvas-notus-data.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "capstone-chart-openvas-notus-data.selectorLabels" . | nindent 4 }}
